### ISSUE TITLE
Add "'post-new.php' === $hook" check in admin_enqueue_scripts function

### ISSUE THREAD

**Issue by philcable** [washingtonstateuniversity/WSU-University-Taxonomy#12]
Specifically for the "edit-post.css" enqueuing. Currently, the "+ Add New Category" link is showing up in the custom taxonomy blocks when creating new pages/posts/etc., which is presumably undesirable.

**Comment by jeremyfelt** [comment]
I apparently have a bad definition of "shortly". This is finally fixed in ff1ed0d6129a11
